// Shared new arrival products array - used by both NewArrivals page and carousel
export type Product = {
  id: string;
  handle: string;
  shopifyVariantId?: string;
  name: string;
  subtitle: string;
  price: string;
  priceNum: number;
  originalPrice?: string;
  category: 'All' | 'Grand Cabinets' | 'Desktop' | 'Travel' | null;
  capacity: string;
  capacityNum: number;
  dimensions?: string;
  material: string;
  finish: string;
  storage: string[];
  humidification: string;
  features: string[];
  description: string;
  image: string;
  images?: string[];
  badge?: string;
  rating?: number;
  reviews?: number;
  isNew: boolean;
};

export const STATIC_PRODUCTS: Product[] = [
  {
    id: 'na-1',
    handle: 'raching-rr980-grand-estate-cigar-humidor',
    name: 'Raching RR980',
    subtitle: 'Grand Estate Cigar Humidor',
    price: '$8,255',
    priceNum: 8255,
    category: 'Grand Cabinets',
    capacity: '3,000–4,000 cigars',
    capacityNum: 4000,
    dimensions: '27.2" W × 27.6" D × 73.4" H',
    material: 'Premium Spanish Cedar shelves & drawers',
    finish: 'Available in Brown & Forest Green',
    storage: [
      '6 Spanish cedar shelves',
      '4 Spanish cedar drawers',
      'Fingerprint + password dual-lock access',
      'Mobile App Remote Unlock',
    ],
    humidification: 'High-Efficiency Water-Cooling · 16–22°C (±1°C) · 60–75% RH (±1%)',
    features: [
      'TFT display with integrated cigar diagnostics',
      'Draw resistance detection — verifies smoking readiness',
      'Fingerprint & password locks + Mobile App unlock',
      'Ammonia removal control for pristine aging',
      'Customizable lighting schedules & brightness',
      '215mm taller than RR880 (+1,000 cigar capacity)',
      '110V/220V global compatibility',
    ],
    description:
      'The RR980 is the definitive grand estate humidor — a monumental cabinet engineered for collectors who demand the absolute apex of environmental precision. TFT diagnostics, draw resistance detection, and mobile app remote unlock place it in a category of its own. Spanish cedar throughout, ammonia removal, and customizable lighting make this the centerpiece of any serious private lounge or tasting room.',
    image: 'https://via.placeholder.com/400x500?text=Raching+RR980',
    badge: 'New',
    rating: 5.0,
    reviews: 3,
    isNew: true,
  },
  {
    id: 'na-2',
    handle: 'raching-ct48a-stainless-steel-grand-humidor',
    name: 'Raching CT48A',
    subtitle: 'Stainless Steel Grand Humidor',
    price: '$6,350',
    priceNum: 6350,
    category: 'Grand Cabinets',
    capacity: '2,500–3,000 cigars',
    capacityNum: 3000,
    dimensions: '27.2" W × 27.6" D × 72.8" H',
    material: 'Spanish cedar interior · Anti-fingerprint stainless steel exterior',
    finish: 'Silver Anti-Fingerprint Stainless Steel',
    storage: [
      '8 layers Spanish cedar shelves',
      '3 slide-rail shelves for deep storage access',
      'Partition boards for brand/strength/age organization',
      'Quick Dehumidification Drawer',
    ],
    humidification: 'Advanced Water-Cooling · 16–22°C (±1°C) · 60–75% RH (±1%)',
    features: [
      'Anti-fingerprint stainless steel exterior',
      'Quick Dehumidification Drawer for rapid moisture reduction',
      'Ammonia Removal Device',
      'Slide-rail shelves for effortless deep access',
      'Partition boards — organize by brand, strength, or age',
      'Silent, stable compressor operation',
    ],
    description:
      'The CT48A is the Pro-User model that marries industrial-grade durability with refined luxury. An anti-fingerprint stainless steel exterior handles the demands of high-traffic environments, while warm Spanish cedar shelves inside ensure flawless cigar preservation. Built for serious collectors, upscale lounges, and boutique cigar retailers who refuse to compromise.',
    image: '/images/products/CT48A-silver.jpg',
    badge: 'New',
    rating: 4.9,
    reviews: 1,
    isNew: true,
  },
  {
    id: 'na-3',
    handle: 'raching-sd800-dual-zone-cigar-wine-cabinet',
    name: 'Raching SD800',
    subtitle: 'Dual-Zone Cigar & Wine Cabinet',
    price: '$7,600',
    priceNum: 7600,
    category: 'Grand Cabinets',
    capacity: '~1,600 cigars · ~130 wine bottles',
    capacityNum: 1600,
    dimensions: '1200 × 610 × 1920 mm · ~190 kg',
    material: 'Spanish cedar (cigar) · Beech wood (wine)',
    finish: 'Refined glass door with wooden accents',
    storage: [
      '8 layers Spanish cedar cigar shelves',
      '9 layers beech wood wine shelves',
      'Independent doors per zone',
    ],
    humidification: 'Integrated water-cooling · Cigar: 16–22°C, 60–75% RH · Wine: 5–22°C',
    features: [
      'Two independently controlled climate zones',
      'Cigar zone: 16–22°C (±1°C), 60–75% RH (±1%)',
      'Wine zone: 5–22°C (±1°C)',
      'Quiet high-performance compressor',
      'Minimal energy loss between zones',
      'Large glass door with refined wooden accents',
      '2-year warranty',
    ],
    description:
      'The SD800 combines precision cigar and wine storage in a single statement cabinet with two fully independent climate zones. Spanish cedar cigar shelves and beech wood wine shelves sit behind a large glass door framed in refined wooden accents — a natural centerpiece for collectors who entertain at the highest level.',
    image: '/images/products/raching-sd800-dual-zone-cigar-wine-cabinet.jpg',
    badge: 'New',
    rating: 4.8,
    reviews: 5,
    isNew: true,
  },
  {
    id: 'na-4',
    handle: 'raching-cs600-luxury-wine-cigar-humidor-cabinet',
    name: 'Raching CS600',
    subtitle: 'Luxury Wine & Cigar Humidor Cabinet',
    price: '$4,450',
    priceNum: 4450,
    category: 'Grand Cabinets',
    capacity: '1,200–1,400 cigars · 100–110 wine bottles',
    capacityNum: 1400,
    dimensions: '1200 W × 610 D × 1760 H mm',
    material: 'Spanish cedar (cigar) · Beech wood (wine)',
    finish: 'Large glass door with digital control panel',
    storage: [
      '7 Spanish cedar cigar shelves',
      '10 beech wood wine shelves',
      'Double-door cabinet design',
    ],
    humidification: 'Dual-zone precision · Wine: 5–22°C · Cigar: 16–22°C, 60–75% RH (±2%)',
    features: [
      'Independent temperature controls per zone',
      'Digital control panel for intuitive management',
      'Whisper-quiet, energy-efficient operation',
      'Spanish cedar lining throughout cigar chamber',
      'Large glass door for 360° collection viewing',
      '2-year warranty',
    ],
    description:
      'The CS600 fuses precision dual-zone climate control with sophisticated design — a double-door cabinet that makes wine and cigar preservation equally effortless. Ideal for private lounges, luxury homes, upscale hotels, and premium retail environments that demand both form and function.',
    image: '/images/products/raching-cs600-luxury-cigar-humidor-cabinet.jpg',
    badge: 'New',
    rating: 4.8,
    reviews: 8,
    isNew: true,
  },
  {
    id: 'na-5',
    handle: 'marciano-countertop-display-humidor-250-cigars',
    name: 'Marciano',
    subtitle: 'Countertop Display Humidor — 250 Cigars',
    price: '$420',
    priceNum: 420,
    category: 'Desktop',
    capacity: 'Up to 250 cigars',
    capacityNum: 250,
    dimensions: '26" W × 11.5" D × 20" H',
    material: 'Spanish cedar trays',
    finish: 'Deep dark mahogany',
    storage: [
      '3 removable & reversible Spanish cedar trays on gold-plated pins',
      '6 adjustable dividers for custom organization',
      'Flexible layout — trays face forward or toward double doors',
    ],
    humidification: 'Two large humidifiers · Calibrated external hygrometer',
    features: [
      '360° view with four glass sides',
      'Magnetic doors with airtight seal',
      'Lock & key set for secure storage',
      'Calibrated external hygrometer',
      'Gold-plated support pins',
      'Deep dark mahogany premium finish',
    ],
    description:
      'The Marciano is a countertop showpiece — four glass sides deliver a complete 360° view of your collection while magnetic airtight doors and two large humidifiers maintain perfect conditions. Gold-plated support pins and deep dark mahogany finish make it equally at home in home bars, offices, luxury lounges, and boutique shops.',
    image: '/images/products/marciano-250-countertop-display.jpg',
    badge: 'New',
    rating: 4.8,
    reviews: 4,
    isNew: true,
  },
  {
    id: 'na-6',
    handle: 'modena-desktop-display-humidor-100-cigars',
    name: 'Modena',
    subtitle: 'Desktop Display Humidor — 100 Cigars',
    price: '$178',
    priceNum: 178,
    category: 'Desktop',
    capacity: 'Up to 100 cigars',
    capacityNum: 100,
    dimensions: '21.5" W × 10" D × 7" H',
    material: 'Spanish cedar interior',
    finish: 'Dark cherry',
    storage: [
      '5 compartments via 4 adjustable Spanish cedar dividers',
      'Internal locking hinges',
    ],
    humidification: '2 gold-polished humidifiers · Built-in hygrometer',
    features: [
      'Angled glass top for effortless at-a-glance viewing',
      'Lock & key set',
      'Internal locking hinges',
      'Elegant gold hardware — handles, lid pull',
      'Built-in hygrometer',
      'Premium dark cherry finish',
    ],
    description:
      'The Modena elevates cigar storage into an architectural experience. An angled glass top, gold hardware, and dark cherry finish combine precision engineering with refined visual character. Perfectly sized for desktop, credenza, or shelf placement — for both the new collector and the seasoned aficionado refining a curated stash.',
    image: '/images/products/modena-cherry-finish-humidor.jpg',
    badge: 'New',
    rating: 4.7,
    reviews: 6,
    isNew: true,
  },
  {
    id: 'na-7',
    handle: 'santiago-end-table-humidor-700-cigars',
    name: 'Santiago',
    subtitle: 'End Table Humidor — 700 Cigars',
    price: '$570',
    priceNum: 570,
    category: 'Desktop',
    capacity: 'Up to 700 cigars',
    capacityNum: 700,
    dimensions: 'End table silhouette with beveled glass top',
    material: 'Spanish cedar lining throughout',
    finish: 'Rich walnut with polished silver hardware',
    storage: [
      '2 smooth-slide pull-out drawers with 3 dividers each',
      'Lower sturdy shelf for boxes & bulk reserves',
      'Lockable sections with lock & key sets',
    ],
    humidification: '6 humidifiers · Silver digital hygrometer visible through glass top',
    features: [
      'Beveled glass top — hygrometer visible at a glance',
      'Embossed wood panels on all sides',
      'Polished silver hardware throughout',
      'Rear wiring port for optional electric upgrade',
      'Doubles as functional furniture end table',
      'Museum-quality sculpted presentation',
    ],
    description:
      'The Santiago fuses timeless craftsmanship with modern practicality — a 700-cigar humidor that doubles as a living room end table. A beveled glass top puts your silver digital hygrometer in plain sight while embossed panels and polished silver hardware ensure it belongs in the finest interiors. For collectors who live with their collection.',
    image: '/images/products/santiago-700-end-table-humidor.jpg',
    badge: 'New',
    rating: 4.8,
    reviews: 7,
    isNew: true,
  },
  {
    id: 'na-8',
    handle: 'traveler-15-travel-humidor-by-humidor-supreme',
    name: 'Traveler 15',
    subtitle: 'Travel Humidor by Humidor Supreme®',
    price: '$42',
    priceNum: 42,
    category: 'Travel',
    capacity: '9–12 cigars',
    capacityNum: 12,
    dimensions: '9" W × 8" D × 2" H',
    material: 'Durable exterior · Built-in humidifier',
    finish: 'Available in Mahogany, Cherry, Burl',
    storage: ['Built-in humidifier', 'Compact travel-ready footprint'],
    humidification: 'Built-in humidifier · Includes XIKAR® Boveda® 60G RH seasoning packs',
    features: [
      'Ready out-of-box with pre-installed humidity packs',
      'Available in Mahogany, Cherry, and Burl finishes',
      'Compact for luggage, backpacks, desk drawers',
      'Durable exterior resistant to travel stress',
      'XIKAR® Boveda® 60G RH included',
    ],
    description:
      'The Traveler 15 is the sleek, travel-ready companion engineered for portability without compromising flavor. Compact enough for luggage or a backpack, it ships ready to use with pre-installed Boveda® humidity packs. Three classic finish options ensure it matches any traveler\'s style.',
    image: '/images/products/portable-cigar-humidor-boveda.png',
    badge: 'New',
    rating: 4.6,
    reviews: 9,
    isNew: true,
  },
  {
    id: 'na-9',
    handle: 'traveler-5-travel-humidor-by-humidor-supreme',
    name: 'Traveler 5',
    subtitle: 'Travel Humidor by Humidor Supreme®',
    price: '$34',
    priceNum: 34,
    category: 'Travel',
    capacity: '8–12 cigars',
    capacityNum: 12,
    dimensions: '8¾" W × 5 11/16" D × 2" H',
    material: 'Sleek Mahogany exterior',
    finish: 'Sleek Mahogany',
    storage: ['Clear acrylic window for inventory check without opening'],
    humidification: 'Built-in humidification · Embedded hygrometer · XIKAR® Boveda® 60G RH',
    features: [
      'Clear acrylic window — check inventory without opening',
      'Embedded hygrometer for real-time humidity monitoring',
      'Built-in humidification system',
      'XIKAR® Boveda® 60G RH seasoning packs included',
      'Fits bags, backpacks, and briefcases',
    ],
    description:
      'The Traveler 5 is the ultimate compact travel companion — a clear acrylic window lets you check your inventory at a glance without ever breaking the seal. Embedded hygrometer, built-in humidification, and included Boveda® packs mean it\'s ready to protect your cigars from the moment it arrives.',
    image: '/images/products/humidor-supreme-traveler-5.png',
    badge: 'New',
    rating: 4.6,
    reviews: 11,
    isNew: true,
  },
  {
    id: 'na-10',
    handle: 'humidor-supreme-electronic-humidor-9000-series-black',
    name: 'Humidor Supreme Electronic Humidor, 9000 Series Black',
    subtitle: 'Electronic Humidor Cabinet',
    price: '$3,550',
    priceNum: 3550,
    category: 'Desktop',
    capacity: '~3,000–4,000 cigars',
    capacityNum: 4000,
    dimensions: 'Electronic cabinet with digital controls',
    material: 'Black exterior with precision controls',
    finish: 'Matte black',
    storage: ['Multiple electronic shelves', 'Digital temperature/humidity display'],
    humidification: 'Electronic precision control · 16–22°C · 60–75% RH',
    features: ['Electronic controls', 'Digital display', 'Precision climate control'],
    description: 'Advanced electronic humidor with precision climate control for serious collectors.',
    image: '/images/products/humidor-supreme-electronic-9000.jpg',
    badge: 'New',
    rating: 4.7,
    reviews: 2,
    isNew: true,
  },
  {
    id: 'na-11',
    handle: 'cigar-tower-shelf-unit-by-humidor-supreme-black',
    name: 'Cigar Tower Shelf Unit by Humidor Supreme Black',
    subtitle: 'Shelf Storage Unit',
    price: '$1,650',
    priceNum: 1650,
    category: 'Desktop',
    capacity: '~2,000 cigars',
    capacityNum: 2000,
    dimensions: 'Tower unit with multiple shelves',
    material: 'Black finish with glass shelves',
    finish: 'Matte black',
    storage: ['Multiple glass shelves', 'Modular tower design'],
    humidification: 'Compatible with Boveda humidity packs',
    features: ['Glass shelving', 'Modular design', 'Elegant tower form'],
    description: 'Elegant tower storage solution for large collections with style and functionality.',
    image: '/images/products/cigar-tower-shelf-unit.jpg',
    badge: 'New',
    rating: 4.6,
    reviews: 4,
    isNew: true,
  },
  {
    id: 'na-12',
    handle: 'traveler-10-desktop-humidor-by-humidor-supreme',
    name: 'Traveler 10 Desktop Humidor by Humidor Supreme',
    subtitle: 'Travel Humidor',
    price: '$30',
    priceNum: 30,
    category: 'Travel',
    capacity: '10–15 cigars',
    capacityNum: 15,
    dimensions: '10" × 7" × 2.5" H',
    material: 'Compact travel-ready construction',
    finish: 'Premium leather exterior',
    storage: ['Built-in humidifier', 'Compact travel footprint'],
    humidification: 'Built-in humidifier · XIKAR® Boveda® included',
    features: ['Ready out-of-box', 'Leather exterior', 'Travel-tested design'],
    description: 'Compact travel humidor perfect for the on-the-go collector.',
    image: '/images/products/traveler-10-desktop-humidor.jpg',
    badge: 'New',
    rating: 4.5,
    reviews: 5,
    isNew: true,
  },
];
