// Static product registry for product pages
// These products are not in Shopify but have dedicated pages

export type StaticProductData = {
  id: string;
  handle: string;
  name: string;
  subtitle: string;
  price: string;
  priceNum: number;
  category: string;
  description: string;
  image: string;
  images: string[];
  features: string[];
  badge?: string;
  rating?: number;
  reviews?: number;
  specs?: Record<string, string>;
};

const STATIC_PRODUCTS: StaticProductData[] = [
  // Cabinet Humidors
  {
    id: 'ch-1',
    handle: 'raching-sd800',
    name: 'Raching SD800',
    subtitle: 'Dual-Zone Cigar & Wine Cabinet',
    price: '$7,600',
    priceNum: 7600,
    category: 'Dual-Zone',
    description: 'The SD800 is the pinnacle of dual-zone preservation — independently controlled cigar and wine compartments in a single showroom-worthy cabinet.',
    image: 'https://dunnluxuryselections.com/cdn/shop/collections/ChatGPT_20Image_20Apr_2016_202026_2005_27_27_20PM_5590c39d-3612-44eb-9dc9-00a747f7a593.png',
    images: [],
    features: ['Dual zones 16–22°C ±1°C, 60–75% RH ±1%', 'Wine zone: 5–22°C ±1°C', 'Advanced airflow & quiet operation', '2-year warranty'],
    badge: 'Flagship',
    rating: 4.9,
    reviews: 7,
    specs: {
      capacity: '~1,600 cigars · ~130 wine bottles',
      dimensions: '1200 × 610 × 1920 mm',
      material: 'Spanish cedar (cigar) · Beech wood (wine)',
      finish: 'Refined glass door with wooden accents',
      humidification: 'Integrated water-cooling · High-performance compressor',
    },
  },
  {
    id: 'ch-2',
    handle: 'raching-cs600',
    name: 'Raching CS600',
    subtitle: 'Luxury Wine & Cigar Humidor Cabinet',
    price: '$4,450',
    priceNum: 4450,
    category: 'Dual-Zone',
    description: 'The CS600 combines wine and cigar storage in an elegant double-door cabinet with independent climate controls.',
    image: 'https://dunnluxuryselections.com/cdn/shop/collections/ChatGPT_20Image_20Apr_2016_202026_2005_27_27_20PM_5590c39d-3612-44eb-9dc9-00a747f7a593.png',
    images: [],
    features: ['Wine zone: 5–22°C ±1°C', 'Cigar zone: 16–22°C, 60–75% RH', 'Whisper-quiet, energy-efficient', '2-year warranty'],
    badge: 'Popular',
    rating: 4.8,
    reviews: 11,
    specs: {
      capacity: '1,200–1,400 cigars · 100–110 wine bottles',
      dimensions: '1200 W × 610 D × 1760 H mm',
      material: 'Spanish cedar (cigar) · Beech wood (wine)',
      finish: 'Large glass door with digital control panel',
      humidification: 'Dual-zone precision climate control',
    },
  },
  {
    id: 'ch-3',
    handle: 'bermuda-cabinet',
    name: 'Bermuda',
    subtitle: 'High-Capacity Collection Cabinet',
    price: '$3,800',
    priceNum: 3800,
    category: 'Classic Cabinet',
    description: 'The Bermuda is built for serious collectors who refuse to compromise on scale. 4,000 cigars, 12 oversized trays, 24 integrated humidifiers.',
    image: 'https://dunnluxuryselections.com/cdn/shop/collections/ChatGPT_20Image_20Apr_2016_202026_2005_27_27_20PM_5590c39d-3612-44eb-9dc9-00a747f7a593.png',
    images: [],
    features: ['Optional touch-activated dimmable LED', 'Rear wiring port for electric upgrades', 'Spanish cedar interior throughout'],
    badge: 'Best Capacity',
    rating: 4.8,
    reviews: 9,
    specs: {
      capacity: '4,000 cigars',
      material: 'Spanish cedar lining',
      finish: 'Dark cherry',
      humidification: '24 built-in humidifiers + external hygrometer',
    },
  },
  {
    id: 'ch-4',
    handle: 'spartacus-cabinet',
    name: 'Spartacus',
    subtitle: 'Showroom-Worthy 1,000-Cigar Cabinet',
    price: '$1,145',
    priceNum: 1145,
    category: 'Classic Cabinet',
    description: 'Three oversized trays with 8 adjustable dividers each, a dedicated pull-out humidifier drawer, and a full-length glass door.',
    image: 'https://dunnluxuryselections.com/cdn/shop/collections/ChatGPT_20Image_20Apr_2016_202026_2005_27_27_20PM_5590c39d-3612-44eb-9dc9-00a747f7a593.png',
    images: [],
    features: ['Full-length framed glass door', 'Brass lock and key', 'Rear wiring port for optional electric upgrade'],
    rating: 4.7,
    reviews: 13,
    specs: {
      capacity: '~1,000 cigars',
      material: 'Spanish cedar interior',
      finish: 'Rich dark cherry',
      humidification: '6 built-in humidifiers + dedicated hygrometer',
    },
  },

  // Desktop Humidors
  {
    id: 'dh-1',
    handle: 'marciano-desktop-humidor',
    name: 'Marciano',
    subtitle: '250-Cigar Countertop Display Humidor',
    price: '$324',
    priceNum: 324,
    category: 'Desktop Humidor',
    description: 'The Marciano commands attention. Four glass sides give a complete 360° view of your collection while deep mahogany woodwork and magnetic airtight doors keep conditions perfect for long-term aging.',
    image: 'https://dunnluxuryselections.com/cdn/shop/files/Marciano_250-cigar_countertop_display_humidor_with_Spanish_cedar_trays.jpg',
    images: [],
    features: ['360° view — 4 glass sides', '3 removable & reversible cedar trays', '6 adjustable dividers', '2 large humidifiers included', 'Calibrated external hygrometer', 'Magnetic doors with airtight seal', 'Lock & key set'],
    badge: 'Bestseller',
    rating: 4.9,
    reviews: 12,
    specs: {
      capacity: 'Up to 250 cigars',
      dimensions: '26" W × 11.5" D × 20" H',
      material: 'Deep dark mahogany',
      interior: 'Spanish cedar trays on gold-plated pins',
    },
  },
  {
    id: 'dh-2',
    handle: 'modena-desktop-humidor',
    name: 'Modena',
    subtitle: '100-Cigar Countertop Display Humidor',
    price: '$138',
    priceNum: 138,
    category: 'Desktop Humidor',
    description: 'The Modena blends countertop elegance with serious capacity. An angled glass lid offers an unobstructed view of up to 100 cigars, while gold-polished hardware elevates every detail.',
    image: 'https://dunnluxuryselections.com/cdn/shop/files/Modena_cherry_finish_humidor_21.5x10x7_inches_perfect_for_countertop_display.jpg',
    images: [],
    features: ['Angled glass top display', '5 compartments with 4 cedar dividers', '2 gold-polished humidifiers', 'Built-in external hygrometer', 'Gold hardware — handles & lid pull', 'Lock & key set', 'Internal locking hinges'],
    badge: 'Featured',
    rating: 4.8,
    reviews: 7,
    specs: {
      capacity: 'Up to 100 cigars',
      dimensions: '21.5" W × 10" D × 7" H',
      material: 'Dark cherry',
      interior: 'Spanish cedar with adjustable dividers',
    },
  },
  {
    id: 'dh-3',
    handle: 'franklin-acrylic-display',
    name: 'Franklin Acrylic Display',
    subtitle: '150-Cigar Acrylic Display Humidor',
    price: '$180',
    priceNum: 180,
    category: 'Desktop Humidor',
    description: "Maximum visibility, minimal footprint. The Franklin's clear acrylic construction turns your collection into a statement piece — 150 cigars on full display with precision humidity control.",
    image: 'https://dunnluxuryselections.com/cdn/shop/files/Franklin_acrylic_display_cigar_humidor_with_clear_body_and_humidifier.jpg',
    images: [],
    features: ['6 open display sections', 'External mount hygrometer', 'Included humidifier', 'Rear access door with lock & key', 'Optional black or wood base', 'Full 360° visibility'],
    badge: 'New',
    rating: 4.7,
    reviews: 4,
    specs: {
      capacity: 'Approximately 150 cigars',
      material: 'Clear acrylic',
      interior: 'Acrylic shelves with 3 fixed dividers',
    },
  },
  {
    id: 'dh-4',
    handle: 'milano-cigar-display',
    name: 'Milano Cigar Display',
    subtitle: '125-Cigar Glass Display Humidor',
    price: '$187',
    priceNum: 187,
    category: 'Desktop Humidor',
    description: "Four tempered glass sides deliver a full 360° showcase for up to 125 cigars. The Milano's dark mahogany frame and angled cedar shelves make it as much a piece of furniture as a humidor.",
    image: 'https://dunnluxuryselections.com/cdn/shop/files/Marciano_250-cigar_countertop_display_humidor_with_Spanish_cedar_trays.jpg',
    images: [],
    features: ['360° view — 4 tempered glass sides', '3 removable angled shelves', 'Adjustable dividers', 'Built-in external hygrometer', 'Included humidifier', 'Lock & key set'],
    rating: 4.6,
    reviews: 5,
    specs: {
      capacity: 'Up to 125 cigars',
      material: 'Dark mahogany',
      interior: 'Spanish cedar-lined trays',
    },
  },
  {
    id: 'dh-5',
    handle: 'duke-desktop-humidor',
    name: 'Duke',
    subtitle: '25–50 Cigar Walnut Humidor',
    price: '$67',
    priceNum: 67,
    category: 'Desktop Humidor',
    description: 'The Duke brings refined walnut craftsmanship to everyday storage. Decorative routed edges and a full cedar interior make this an exceptional choice for personal collections of 25–50 cigars.',
    image: 'https://dunnluxuryselections.com/cdn/shop/files/duke-routed-edge-desktop-cigar-humidor.jpg',
    images: [],
    features: ['Decorative routed edge detail', 'Adjustable cedar divider', 'Built-in hygrometer', 'Humidifier included', 'Scratch-resistant felt bottom', 'Internal locking hinges'],
    rating: 4.7,
    reviews: 9,
    specs: {
      capacity: '25–50 cigars',
      dimensions: '10¼" W × 8¾" D × 4¼" H',
      material: 'Walnut',
      interior: 'Full Spanish cedar lining',
    },
  },
  {
    id: 'dh-6',
    handle: 'vizcaya-ebony',
    name: 'Vizcaya Ebony',
    subtitle: '25–50 Cigar Ebony Humidor',
    price: '$54',
    priceNum: 54,
    category: 'Desktop Humidor',
    description: 'Genuine ebony veneer gives the Vizcaya a deep, dramatic grain that stands apart from standard wood-finished humidors. A polished silver hygrometer completes the striking contrast.',
    image: 'https://dunnluxuryselections.com/cdn/shop/files/vizcaya-ebony-desktop-cigar-humidor.jpg',
    images: [],
    features: ['Authentic ebony veneer exterior', 'Adjustable cedar divider', 'Polished silver hygrometer', 'Removable humidifier', 'Internal locking hinges', 'Low-profile wide design'],
    rating: 4.6,
    reviews: 3,
    specs: {
      capacity: '25–50 cigars',
      dimensions: '11" W × 8.5" D × 3.25" H',
      material: 'Authentic ebony wood veneer',
      interior: 'Rich Spanish cedar',
    },
  },
  {
    id: 'dh-7',
    handle: 'vizcaya-makore-pommele',
    name: 'Vizcaya Makore Pommele',
    subtitle: '25–50 Cigar Makore Pommele Humidor',
    price: '$54',
    priceNum: 54,
    category: 'Desktop Humidor',
    description: 'The rare Makore Pommele veneer produces a distinctive chatoyant grain pattern — no two boxes look the same. Full Spanish cedar interior ensures proper humidity retention.',
    image: 'https://dunnluxuryselections.com/cdn/shop/files/vizcaya-makorem-pommele-desktop-cigar-humidor.jpg',
    images: [],
    features: ['Makore Pommele wood veneer', 'Adjustable divider', 'Polished silver hygrometer', 'Included humidifier', 'Internal locking hinges', 'Low-profile wide design'],
    rating: 4.8,
    reviews: 1,
    specs: {
      capacity: '25–50 cigars',
      material: 'Makore Pommele — natural striking grain',
      interior: 'Full Spanish cedar lining',
    },
  },
  {
    id: 'dh-8',
    handle: 'chalet-glasstop-cherry',
    name: 'Chalet Glasstop (Cherry)',
    subtitle: '25–50 Cigar Glasstop Humidor',
    price: '$43',
    priceNum: 43,
    category: 'Desktop Humidor',
    description: 'Classic cherry finish meets modern glass-top design. The Chalet Glasstop lets you view your cigars at a glance while maintaining the ideal cedar environment inside.',
    image: 'https://dunnluxuryselections.com/cdn/shop/files/chalet-glasstop-cherry-desktop-cigar-humidor.jpg',
    images: [],
    features: ['Tempered glass top display', 'External hygrometer', 'Included humidifier', 'Adjustable divider', 'Scratch-resistant felt bottom', 'Internal locking hinges'],
    rating: 4.5,
    reviews: 6,
    specs: {
      capacity: '25–50 cigars',
      dimensions: '10½" W × 8¾" D × 4¼" H',
      material: 'Rich cherry with glass top',
      interior: 'Spanish cedar lining',
    },
  },
  {
    id: 'dh-9',
    handle: 'chalet-glasstop-black',
    name: 'Chalet Glasstop (Black)',
    subtitle: '25–50 Cigar Glasstop Humidor',
    price: '$43',
    priceNum: 43,
    category: 'Desktop Humidor',
    description: 'A sleek, contemporary take on the classic glasstop humidor. The deep black exterior creates a dramatic contrast with the warm Spanish cedar interior.',
    image: 'https://dunnluxuryselections.com/cdn/shop/files/chalet-glasstop-black-desktop-cigar-humidor.jpg',
    images: [],
    features: ['Transparent glass lid', 'External hygrometer', 'Included humidifier', 'Adjustable divider', 'Scratch-resistant felt bottom', 'Internal locking hinges'],
    rating: 4.5,
    reviews: 4,
    specs: {
      capacity: '25–50 cigars',
      dimensions: '10½" W × 8¾" D × 4¼" H',
      material: 'Deep black with glass top',
      interior: 'Spanish cedar lining',
    },
  },
  {
    id: 'dh-10',
    handle: 'chardonnay-desktop-humidor',
    name: 'Chardonnay',
    subtitle: 'Up to 50 Cigar Walnut Humidor',
    price: '$42',
    priceNum: 42,
    category: 'Desktop Humidor',
    description: 'Dark walnut exterior with solid brass locking hinges — the Chardonnay is a refined everyday humidor with premium construction details at an accessible price.',
    image: 'https://dunnluxuryselections.com/cdn/shop/files/chateau-glasstop-cherry-cigar-humidor.jpg',
    images: [],
    features: ['Authentic dark walnut exterior', 'Dedicated hygrometer', 'Integrated humidifier', 'Adjustable divider', 'Scratch-resistant felt bottom', 'Solid brass locking hinges'],
    rating: 4.6,
    reviews: 1,
    specs: {
      capacity: 'Up to 50 cigars',
      dimensions: '10½" W × 8¾" D × 4¼" H',
      material: 'Authentic dark walnut',
      interior: 'Spanish cedar lining',
    },
  },
  {
    id: 'dh-11',
    handle: 'chalet-cherry',
    name: 'Chalet (Cherry)',
    subtitle: '25–50 Cigar Cherry Humidor',
    price: '$36',
    priceNum: 36,
    category: 'Desktop Humidor',
    description: 'The entry point to the Chalet family — honest cherry woodwork, full cedar interior, and everything you need to keep 25–50 cigars in perfect condition.',
    image: 'https://dunnluxuryselections.com/cdn/shop/files/chalet-cherry-desktop-cigar-humidor.jpg',
    images: [],
    features: ['Built-in hygrometer', 'Integrated humidifier', 'Adjustable divider', 'Scratch-resistant felt bottom', 'Internal locking hinges'],
    rating: 4.4,
    reviews: 8,
    specs: {
      capacity: '25–50 cigars',
      dimensions: '10½" W × 8¾" D × 4¼" H',
      material: 'Rich cherry wood',
      interior: 'Full Spanish cedar lining',
    },
  },
  {
    id: 'dh-12',
    handle: 'chalet-black',
    name: 'Chalet (Black)',
    subtitle: 'Up to 20 Cigar Glasstop Humidor',
    price: '$36',
    priceNum: 36,
    category: 'Desktop Humidor',
    description: 'Compact, elegant, and purpose-built for personal collections. The Chalet Black keeps up to 20 cigars at peak condition in a slim glass-top profile.',
    image: 'https://dunnluxuryselections.com/cdn/shop/files/chalet-black-glass-top-cigar-humidor.jpg',
    images: [],
    features: ['Glass-top lid', 'Built-in hygrometer', 'Removable humidifier', 'Internal locking hinges', 'Felt-lined bottom'],
    rating: 4.4,
    reviews: 5,
    specs: {
      capacity: 'Up to 20 cigars',
      dimensions: '9" W × 8.5" D × 2.25" H',
      material: 'Black exterior with glass top',
      interior: 'Spanish cedar lining',
    },
  },
];

export function getStaticProduct(handle: string): StaticProductData | undefined {
  return STATIC_PRODUCTS.find((p) => p.handle === handle);
}

export function getAllStaticProducts(): StaticProductData[] {
  return STATIC_PRODUCTS;
}
