name = "dls-belle1"
pages_build_output_dir = "./dist"
compatibility_date = "2026-05-05"

[vars]
KLAVIYO_LIST_ID = "W3FA6q"
VITE_SHOPIFY_STORE_DOMAIN = "luxury-dunn-selections.myshopify.com"
VITE_SHOPIFY_STOREFRONT_TOKEN = "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"
VITE_SHOPIFY_SHOP_PAY_CLIENT_ID = "a0394747672f29da45ef895b3411132"
VITE_SHOPIFY_SHOP_PAY_SECRET = "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2"
SHOPIFY_STORE_DOMAIN = "luxury-dunn-selections.myshopify.com"
SHOPIFY_SHOP_PAY_CLIENT_ID = "a0394747672f29da45ef895b3411132"
SHOPIFY_SHOP_PAY_SECRET = "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2"
